# Generated by Django 4.2.5 on 2023-09-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exist_since',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
