# Generated by Django 4.2.5 on 2023-09-27 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_user_exist_since'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='exist_since',
        ),
    ]
