# Generated by Django 4.2.5 on 2023-09-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_user_rename_recension_blog_rate_remove_blog_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.CharField(default=0, max_length=1024),
            preserve_default=False,
        ),
    ]
