# Generated by Django 4.2.5 on 2023-09-20 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_comment_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='rate',
            new_name='avg_rate',
        ),
    ]
