# Generated by Django 4.2.5 on 2023-09-28 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('projectapp', '0003_remove_user_exist_since'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('myuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='projectapp.user')),
            ],
            bases=('authtoken.token',),
        ),
    ]
