# Generated by Django 4.2.5 on 2023-09-20 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_rename_rate_blog_avg_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='avg_rate',
            new_name='rate',
        ),
    ]
