# Generated by Django 4.2.5 on 2023-09-28 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
