# Generated by Django 4.2.5 on 2023-09-21 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0006_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='rate',
        ),
    ]
