# Generated by Django 4.2.5 on 2023-09-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0007_remove_blog_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='average_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
