# Generated by Django 4.2.5 on 2023-09-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0009_alter_blog_date_created_alter_blog_date_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
