# Generated by Django 3.2.21 on 2023-10-01 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0009_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
    ]
