# Generated by Django 4.2.5 on 2023-09-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0011_alter_blog_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recension',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
